### ISSUE TITLE
Upgrading to grunt-phantomflow 1.0.0 will not run tests.

### ISSUE THREAD

**Issue by webedge** [Huddle/grunt-phantomflow#11]
We had been using 0.2.4 for some time and have upgraded our package.json to refer to 1.0.0.

We need to upgrade to 1.0.0 since it has an upgraded version of PhantomJS as a child dependency.

After we did a npm cache clean and install, our tests no longer run. 
![capture](https://cloud.githubusercontent.com/assets/1932544/14990577/ceb2f39c-1122-11e6-98bd-69b72d9f63bc.PNG)

**Comment by eskitek** [comment]
We've got some more info on this.

To reproduce the issue, get latest from the grunt-phantomflow git repo. Delete phantomcss from the node_modules directory and do an npm install. This should cause it to download phantomcss v1.1.1 (you must be using v1.1.1 to recreate the issue). Then run the example test project per the readme:

```
node test/test.js
```

This results in the error:

```
\PhantomFlow\node_modules\wrench\lib\wrench.js:249
        if (e.code !== 'EEXIST') throw e;
                                       ^
Error: ENOENT, no such file or directory '\PhantomFlow\test-results\r
eport'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at Object.exports.copyDirSyncRecursive (\PhantomFlow\node_modules
\wrench\lib\wrench.js:246:12)
    at copyReportTemplate (\PhantomFlow\phantomflow.js:554:10)
    at \PhantomFlow\phantomflow.js:500:7
    at null.<anonymous> (\PhantomFlow\node_modules\async\lib\async.js
:789:30)
    at null._onTimeout (\PhantomFlow\node_modules\async\lib\async.js:
167:37)
    at Timer.listOnTimeout (timers.js:110:15)
```

We've done some digging/experimenting and have some more information around what's causing this issue. It seems to be caused by a change to phantomcss.js in commit 0c12049f5cd281c7f5f798f812c5209642b96bbe (phantomcss v 1.1.1). The problem does not exist if we drop in the previous revision of phantomcss.js.

The problem seems to be caused by the fact that the phantomcss function getResemblePath does not use root to build the path to resemble.js when root is provided. See [line 124](https://github.com/Huddle/PhantomCSS/commit/0c12049f5cd281c7f5f798f812c5209642b96bbe#diff-f7f814c0b1ff21fbac0dcdc2e25ee0e3R124):

```
path = [ './', 'node_modules', 'resemblejs', 'resemble.js' ].join( fs.separator );
```

If I understand what's going on here, if root is provided, getResemblePath should build the path to resemble.js using root as its base directory. When we change line 124 to the following, the example test project starts working again:

```
path = [ root, 'node_modules', 'resemblejs', 'resemble.js' ].join( fs.separator );
```

In all honesty, I don't quite understand why this code change resulted in the error we were seeing. Our error seems to occur when copying the report templates to the test results folder, not when trying to use resemblejs. But none the less, fixing the above issue gets rid of the error we are seeing.

I'm happy to submit a pull request for this, but since I was not 100% sure of the intent of the code change in the first place, I wanted to run it by you first. Also, I'm not sure whether or not [line 126](https://github.com/Huddle/PhantomCSS/commit/0c12049f5cd281c7f5f798f812c5209642b96bbe#diff-f7f814c0b1ff21fbac0dcdc2e25ee0e3R126) should be using root as its base directory too.

If you could provide some confirmation/guidance here, I'll submit a pull request.

**Comment by jamescryer** [comment]
Thanks, Emily.

PhantomCSS 1.1.1 was a PR and then a fix (for that PR) to make resolution of libraries more robust.  Looks like I didn't test thoroughly enough, sorry about that (We're not currently using it in-house).

If you'd like to submit a PR - I'll review and test early next week.
